language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
            - gfortran
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install: 
  - curl https://blas-lapack-rs.github.io/travis/fortran.sh | bash

#before_cache: |
# if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
#   cargo install cargo-tarpaulin
# fi

script:
- cargo install cargo-all-features
- cargo build-all-features
- cargo test --all-features

# after_success: |
# if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
# fi
